name: Run Test Environment

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run env:test script
        run: npm run env:test

      - name: Archive Playwright test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-test-results
          path: |
            **/test-results/**
          if-no-files-found: warn
